name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: cspell-action
        uses: streetsidesoftware/cspell-action@v2.0.1
        with:
          incremental_files_only: false
