name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank You for opening an issue. These help us make The big6 Project better.'
        pr-message: 'Thank You for creating a pull request. These motivate us that the community is with us to help. Thanks again for your first contribution towards The big6 Project.'
